"""schema inicial

Revision ID: 08ab5ddc7a6a
Revises: 
Create Date: 2026-07-02 18:13:19.479235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ab5ddc7a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('tamanho_habitual', sa.String(length=5), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=True),
    sa.Column('logradouro', sa.String(length=160), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('max_usos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('fornecedor', sa.String(length=160), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('estoque', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametros',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('colecao', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('custo_mao_de_obra', sa.Float(), nullable=False),
    sa.Column('custos_extras', sa.Float(), nullable=False),
    sa.Column('margem_percentual', sa.Float(), nullable=False),
    sa.Column('preco_etiqueta', sa.Float(), nullable=False),
    sa.Column('preco_promocional', sa.Float(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=True),
    sa.Column('peso_g', sa.Float(), nullable=False),
    sa.Column('altura_cm', sa.Float(), nullable=False),
    sa.Column('largura_cm', sa.Float(), nullable=False),
    sa.Column('comprimento_cm', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=5), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('reservado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kit_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentos_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=5), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_producao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=5), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_producao.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peca_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('valor_inicial', sa.Float(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frete', sa.Float(), nullable=False),
    sa.Column('frete_cortesia', sa.Boolean(), nullable=False),
    sa.Column('marketplace_pct', sa.Float(), nullable=False),
    sa.Column('desconto_total', sa.Float(), nullable=False),
    sa.Column('cupom_codigo', sa.String(length=40), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('comprador', sa.String(length=160), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('estoque_baixado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('forma', sa.String(length=40), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('taxa_pct', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=5), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_itens')
    op.drop_table('pagamentos')
    op.drop_table('vendas')
    op.drop_table('vales')
    op.drop_table('peca_insumos')
    op.drop_table('ordem_producao_itens')
    op.drop_table('movimentos_peca')
    op.drop_table('movimentos_estoque')
    op.drop_table('kit_itens')
    op.drop_table('fotos_peca')
    op.drop_table('estoque_pecas')
    op.drop_table('pecas')
    op.drop_table('parametros')
    op.drop_table('ordens_producao')
    op.drop_table('kits')
    op.drop_table('insumos')
    op.drop_table('despesas')
    op.drop_table('cupons')
    op.drop_table('clientes')
    # ### end Alembic commands ###
